#!/bin/bash
gnaf_dir="/usr/lib/python2.7/site-packages/gnaf"
settings_dir="${HOME}/.gnaf/settings.py"
if [ ! -d "$gnaf_dir" ]; then
    echo 'Install gnaf first.'    
else
    if [ $1 == "" ]; then
        echo 'No applet name given'
    else
        applet=$1
        applet_repo="git://github.com/Kantist/gnaf-${applet}.git"
        git clone "${applet_repo}"
        #cp -r "gnaf-${applet}" "${gnaf_dir}/applets/${applet}"
        echo '' >> "${settings_dir}"
        echo "${applet} = {'applet':'${applet}'}" >> "${settings_dir}"
        echo "Applet ${applet} has been succesfully installed."
        echo "  Configure the applet in ~/.gnaf/settings.py."
    fi
fi
exit 0
